services:
  ingolstadt-parkplatzauskunft:
    container_name: ingolstadt-parkplatzauskunft
    image: ghcr.io/dieechtenilente/ingolstadt-parkplatzauskunft/ingolstadt-parkplatzauskunft:latest
    restart: unless-stopped
    volumes:
      - ./output:/opt/script/output
    environment:
      - PASSWORD=password
      - USERNAME=username
      - URL=https://example.com
      - OUTPUT_FILE=file.json